#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6443694484                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : jp                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://itunes.apple.com/app/id6443694484                                         # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                       # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : OneMoreList                                            # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : OneMoreList - Shopping list app that can be shared with family and friends

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Swallow Works Studio                            
your_link                                 : http://kakeibo.swalloworkstudio.com                     
your_city                                 : Tokyo                                
email_address                             : swalloworks@gmail.com
facebook_username                         : mainichishoppinglist                                          
instagram_username                        : 
twitter_username                          : swalloworks
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Share with your family and friends
    description                           : The list content is updated in real time on the shared destination.
    fontawesome_icon_name                 : magic
    
  - title                                 : Input auto-completion
    description                           : It automatically completes the product name that matches the entered string.
    fontawesome_icon_name                 : heartbeat
  
  - title                                 : Automatic synchronization
    description                           : The content of the list is automatically synchronized between iPhones / iPads / M1 Macs with the same Apple ID.
    fontawesome_icon_name                 : sync

  - title                                 : Local first
    description                           : All data is saved locally first. Even if you are not connected to the network, you can check or edit the list content.
    fontawesome_icon_name                 : bell

  - title                                 : Security
    description                           : The data is yours. Even if you are a developer, you cannot view or edit the data.
    fontawesome_icon_name                 : star

  - title                                 : No login required
    description                           : If you have an AppleID account, you can use it without logging in.
    fontawesome_icon_name                 : adjust



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.5

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff" 
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
